---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec
  inspec_tests:
    - test/smoke/default

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: test
    run_list:
      - recipe[test::asdf_user_install]
      - recipe[test::asdf_script]
      - recipe[test::asdf_plugin]
      - recipe[test::asdf_package]
