---
driver:
  name: dokken
  privileged: true
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
# Amazon Linux 2 can't be fully tested yet on Test Kitchen because the inspec
# tests error out due to a bug in the current train 1.5.6 gem. The issue has
# been fixed in version 1.5.10, but that hasn't been released yet. Until then,
# we can converge the test and see that everything runs without errors.
# https://github.com/inspec/train/blob/v1.5.6/lib/train/platforms/detect/helpers/os_linux.rb#L13
#
- name: amazonlinux-2
  driver:
    image: dokken/amazonlinux-2
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
    - RUN /usr/bin/yum -y update

- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
    - RUN /usr/bin/yum -y update

- name: debian-8
  driver:
    image: dokken/debian-8
    pid_one_command: /bin/systemd
    intermediate_instructions:
    - RUN /usr/bin/apt-get update

- name: debian-9
  driver:
    image: dokken/debian-9
    pid_one_command: /bin/systemd
    intermediate_instructions:
    - RUN /usr/bin/apt-get update

- name: fedora-27
  driver:
    image: dokken/fedora-27
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
    - RUN /usr/bin/yum -y update

- name: fedora-28
  driver:
    image: dokken/fedora-28
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
    - RUN /usr/bin/yum -y update

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
    - RUN /usr/bin/apt-get -y update
    - RUN /usr/bin/apt-get install -y sudo

- name: ubuntu-18.04
  driver:
    image: dokken/ubuntu-18.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
    - RUN /usr/bin/apt-get -y update
    - RUN /usr/bin/apt-get install -y sudo

suites:
- name: test
  run_list:
  - recipe[test::vagrant]
  - recipe[test::asdf_user_install]
  - recipe[test::asdf_script]
  - recipe[test::asdf_plugin]
  - recipe[test::asdf_package]
  verifier:
    inspec_tests:
    - test/smoke/default/asdf_test.rb
