---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
- name: centos-7
- name: debian-8
- name: debian-9
- name: fedora-27
- name: fedora-28
- name: ubuntu-14.04
- name: ubuntu-16.04
- name: ubuntu-18.04

suites:
- name: test
  run_list:
  - recipe[test::asdf_user_install]
  - recipe[test::asdf_script]
  - recipe[test::asdf_plugin]
  - recipe[test::asdf_package]
  verifier:
    inspec_tests:
    - test/smoke/default/asdf_test.rb
