---
driver:
  name: dokken
  privileged: true
  chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
    - RUN /usr/bin/yum -y update
- name: fedora-27
  driver:
    image: dokken/fedora-27
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
    - RUN /usr/bin/yum -y update
- name: fedora-28
  driver:
    image: dokken/fedora-28
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
    - RUN /usr/bin/yum -y update
- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
    - RUN /usr/bin/apt-get -y update
    - RUN /usr/bin/apt-get install -y sudo
- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
    - RUN /usr/bin/apt-get -y update
    - RUN /usr/bin/apt-get install -y sudo
- name: ubuntu-18.04
  driver:
    image: dokken/ubuntu-18.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
    - RUN /usr/bin/apt-get -y update
    - RUN /usr/bin/apt-get install -y sudo

suites:
- name: test
  run_list:
  - recipe[test::vagrant]
  - recipe[test::asdf_user_install]
  - recipe[test::asdf_script]
  - recipe[test::asdf_plugin]
  - recipe[test::asdf_package]
  verifier:
    inspec_tests:
    - test/smoke/default/asdf_test.rb
