---
driver:
  name: vagrant

provisioner:
  product_name: chefdk

verifier:
  name: inspec

platforms:
- name: amazonlinux-2
  driver_config:
    box: gbailey/amzn2
- name: centos-7
- name: debian-8
- name: debian-9
- name: fedora-27
- name: fedora-28
- name: ubuntu-16.04
- name: ubuntu-18.04

suites:
- name: package
  run_list:
  - recipe[test::package]

- name: plugin
  run_list:
  - recipe[test::plugin]

- name: script
  run_list:
  - recipe[test::script]

- name: user_install
  run_list:
  - recipe[test::user_install]
