sudo: required
dist: trusty

addons:
  apt:
    sources:
    - chef-current-trusty
    packages:
    - chefdk

install: echo "skip bundle install"

branches:
  only:
  - master

services: docker

env:
  matrix:
  - INSTANCE=package-amazonlinux-2
  - INSTANCE=package-centos-7
  - INSTANCE=package-debian-8
  - INSTANCE=package-debian-9
  - INSTANCE=package-fedora-27
  - INSTANCE=package-fedora-28
  - INSTANCE=package-ubuntu-1604
  - INSTANCE=package-ubuntu-1804
  - INSTANCE=plugin-amazonlinux-2
  - INSTANCE=plugin-centos-7
  - INSTANCE=plugin-debian-8
  - INSTANCE=plugin-debian-9
  - INSTANCE=plugin-fedora-27
  - INSTANCE=plugin-fedora-28
  - INSTANCE=plugin-ubuntu-1604
  - INSTANCE=plugin-ubuntu-1804
  - INSTANCE=script-amazonlinux-2
  - INSTANCE=script-centos-7
  - INSTANCE=script-debian-8
  - INSTANCE=script-debian-9
  - INSTANCE=script-fedora-27
  - INSTANCE=script-fedora-28
  - INSTANCE=script-ubuntu-1604
  - INSTANCE=script-ubuntu-1804
  - INSTANCE=user-install-amazonlinux-2
  - INSTANCE=user-install-centos-7
  - INSTANCE=user-install-debian-8
  - INSTANCE=user-install-debian-9
  - INSTANCE=user-install-fedora-27
  - INSTANCE=user-install-fedora-28
  - INSTANCE=user-install-ubuntu-1604
  - INSTANCE=user-install-ubuntu-1804

before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- chef --version
- cookstyle --version
- foodcritic --version

script: CHEF_LICENSE="accept-no-persist" KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

after_script:
- docker images
- docker ps -a
- cat .kitchen/logs/kitchen.log

matrix:
  include:
  - script:
    - delivery local verify
    env: UNIT_AND_LINT=1
