sudo: required
dist: trusty

addons:
  apt:
    sources:
    - chef-current-trusty
    packages:
    - chefdk

install: echo "skip bundle install"

branches:
  only:
  - master

services: docker

env:
  matrix:
  - INSTANCE=test-centos-7
  - INSTANCE=test-debian-8
  - INSTANCE=test-debian-9
  - INSTANCE=test-fedora-27
  - INSTANCE=test-fedora-28
  - INSTANCE=test-ubuntu-1604
  - INSTANCE=test-ubuntu-1804
  - INSTANCE=script-centos-7
  - INSTANCE=script-debian-8
  - INSTANCE=script-debian-9
  - INSTANCE=script-fedora-28
  - INSTANCE=script-fedora-29
  - INSTANCE=script-ubuntu-1604
  - INSTANCE=script-ubuntu-1804
  - INSTANCE=user-install-centos-7
  - INSTANCE=user-install-debian-8
  - INSTANCE=user-install-debian-9
  - INSTANCE=user-install-fedora-28
  - INSTANCE=user-install-fedora-29
  - INSTANCE=user-install-ubuntu-1604
  - INSTANCE=user-install-ubuntu-1804

before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- chef --version
- cookstyle --version
- foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

after_script:
- docker images
- docker ps -a
- cat .kitchen/logs/kitchen.log

matrix:
  include:
  - script:
    - delivery local verify
    env: UNIT_AND_LINT=1
