---
lint_and_unit: &lint_and_unit
  - delivery
  - lint-yaml
  - lint-markdown

version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2

workflows:
  kitchen:
    jobs:
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/delivery:
          name: delivery
      - kitchen/dokken-single:
          name: default-centos-7
          suite: default-centos-7
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-debian-9
          suite: default-debian-9
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-debian-10
          suite: default-debian-10
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-fedora-27
          suite: default-fedora-27
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-fedora-28
          suite: default-fedora-28
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-ubuntu-1604
          suite: default-ubuntu-1604
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-ubuntu-1804
          suite: default-ubuntu-1804
          requires:
            *lint_and_unit
